In [3]:
import numpy as np
from sipbuild.generator.parser.tokens import states

In [16]:
a = np.array([1,2,3,4,5], dtype= 'int16')
print(a)

[1 2 3 4 5]


In [7]:
b = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
# Get dimension
a.ndim


1

In [12]:
b.ndim

2

In [13]:
b.shape

(2, 5)

In [17]:
# Get type
a.dtype

dtype('int16')

In [18]:
# Get Size
a.itemsize

2

In [26]:


# Get total size

a.nbytes


10

be carefull while copying arrays


In [ ]:
output = np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4, 1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
np.matmul(a,b)
np.identity(3)
np.linalg.det(a)
np.linalg.inv(a)



[1 2 3 4 5]


Statistics


In [38]:
stats= np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.min(stats)

np.int64(1)